# Dependencies
markdown: kramdown

encoding: "utf-8"

# Configuration
destination: build
source: src

# Setup
title: Particle41
email: info@particle41.com
description: ''

# Stuff
exclude: ['event-samples']
keep_files: ['css', 'js']

# Do not process but copy to build.
vendor:
  source: '_vendor'
  destination: 'vendor'


# Global handlers
disqus_shortname: particle41
meta_description: 'Particle41 partners with key cloud infrastructure, automation, and management providers to ensure our clients take advantage of the best cloud solutions available.'
staging_host: stagingwwwparticle41

# Collections
collections:
  projects:
    output: true

assets:
  compress:
    css: true
  digest: true
  sources:
    - css

sass:
    sass_dir: css

# gems:
#   - jekyll-assets

