version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync build/ s3://hitesh-p41.github.io
